language: node_js
node_js:
  - "8"
services: mongodb
cache:
  yarn: true
install:
  - yarn install
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - yarn test
