version: '2'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 1234:8000
    links:
      - mongo
  mongo:
    image: mongo:latest
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - ./db:/data/db
